### ISSUE TITLE
看github上go原生crypto/aes库是2年前就已经支持AES-128, AES-192, or AES-256.

### ISSUE THREAD

**Issue by 308066400** [chentaihan/aesCbc#4]
而且是带asm汇编支持cpu aesni指令那种，相对没有支持cpu aes指令的效率相差三倍。。。

https://github.com/golang/go/tree/master/src/crypto/aes

**Comment by chentaihan** [comment]
![image](https://user-images.githubusercontent.com/3400991/91928890-c09c9100-ed0f-11ea-95be-fe038846913d.png)
并没有实现256位的加密解密，const BlockSize = 16，一次还是加密128位，
我为什么要自己实现256位加密解密，这篇文章说得很清楚：https://www.cnblogs.com/hlxs/p/9852594.html
