### ISSUE TITLE
你提供的生成256的加密字符串，跟其他网站上生成的不一致。怎么办

### ISSUE THREAD

**Issue by liyantaotop** [chentaihan/aesCbc#5]
![image](https://user-images.githubusercontent.com/20124333/103726098-0c8b7980-5013-11eb-9d6b-85b273d3406c.png)

**Comment by liyantaotop** [comment]
加密内容是 123456

**Comment by liyantaotop** [comment]
我拿你单元测试的数据 到网站上尝试加密。提示key 长度不是32 或者  256 bytes

**Comment by chentaihan** [comment]
那是因为人家对秘钥长度做了限制，可以换个网站试试
